### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by cabmoomoo** [cabmoomoo/dsp-calculator#1]
To-do list on updating and improving calculator

### Updating

- [x] Generate item and recipe lists directly from game files
- [ ] Modify generated lists and/or parsing code for compatibility
   - [ ] Simplify generated JSON to only contain what is need
   - [ ] Create script to add data to belts (rate) and buildings (speed)
   - [ ] Recipies
